application: gae-webapp2-skeleton
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /.*
  script: main.app

builtins:
- deferred: on

libraries:
- name: jinja2
  version: "2.6"
